---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::r-argparse=2.2.5
- conda-forge::r-data.table=1.17.8
- conda-forge::r-dplyr=1.1.4
- conda-forge::r-plyr=1.8.9
- conda-forge::r-tidyverse=2.0.0
