---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-argparse=2.3.1
  - conda-forge::r-data.table=1.17.8
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-ggforce=0.5.0
  - conda-forge::r-ggiraph=0.8.12
  - conda-forge::r-gtools=3.9.5
  - conda-forge::r-htmlwidgets=1.6.4
  - conda-forge::r-plotly=4.11.0
  - conda-forge::r-plyr=1.8.9
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-scales=1.4.0
  - conda-forge::r-tidyverse=2.0.0
